### ISSUE TITLE
Wie richte ich das ein?

### ISSUE THREAD

**Issue by byZeroOfficial** [joseywoermann/kgh-notifier#4]
Wie bringe ich die BAT zum laufen? Mussiä ich sie mehrmals ausführen oder läuft sie in Hintergrund.

**Comment by joseywoermann** [comment]
Rinfach einmal die .bat starten. Das ist eine `while True` Schleife.

**Comment by joseywoermann** [comment]
Erstmal `pip install requests` und `pip install beautifulsoup4`

**Comment by byZeroOfficial** [comment]
Phyton muss ich aber zuerst installieren?

**Comment by joseywoermann** [comment]
> Phyton muss ich aber zuerst installieren?

Ja natürlich

**Comment by joseywoermann** [comment]
@byZeroOfficial Ich schließe das hier, wenn du Hilfe brauchst kannst du es ja wieder öffnen.
